name: 'Infrastructure Management Action'
description: 'Manage infrastructure deployments with Terragrunt'
inputs:
  action:
    description: 'Action to perform (plan/apply/destroy)'
    required: true
    default: 'plan'
  environment:
    description: 'Target environment (dev/test/prod)'
    required: true
    default: 'dev'
  project_id:
    description: 'Project ID for infrastructure'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true
  argocd_repo:
    description: 'ArgoCD configuration repository'
    required: true
  working_dir:
    description: 'Working directory for infrastructure code'
    required: false
    default: 'clusters'
  terraform_version:
    description: 'Terraform version to use'
    required: false
    default: '1.9.7'
  terragrunt_version:
    description: 'Terragrunt version to use'
    required: false
    default: '0.67.16'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'cloud'
  color: 'blue'
